package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * Account generated by hbm2java
 */
@Entity
@Table(name = "account", catalog = "cloud")
public class Account extends GenIdEntityImpl {

	@Override
	public String toString() {
		return "Account [账户明年=" + user + ", 办理时间=" + procTime + ", 创建时间="
				+ createTime + ", 过期=" + expirationTime + ", 余额=" + balance
				+ "]";
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -2321089888840509961L;
	private User user; // 账户对应的用户
	private Date procTime; // 办理时间
	private Date createTime; // 创建时间
	private Date beginTime; // 会员开始时间
	private Date expirationTime; // 长期会员时效时间
	private double balance; // 余额

	@PrePersist
	public void prePersist() {
		createTime = new Date();
	}

	public Account() {
	}

	public Account(User user, Date createTime, double balance) {
		this.user = user;
		this.createTime = createTime;
		this.balance = balance;
	}

	public Account(User user, Date createTime, Date procTime,
			Date expirationTime, double balance) {
		this.user = user;
		this.createTime = createTime;
		this.procTime = procTime;
		this.expirationTime = expirationTime;
		this.balance = balance;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "proc_time", nullable = false, length = 19)
	public Date getProcTime() {
		return this.procTime;
	}

	public void setProcTime(Date procTime) {
		this.procTime = procTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "expiration_time", length = 10)
	public Date getExpirationTime() {
		return this.expirationTime;
	}

	public void setExpirationTime(Date expirationTime) {
		this.expirationTime = expirationTime;
	}

	@Column(name = "balance", nullable = false, precision = 10)
	public double getBalance() {
		return this.balance;
	}

	public void setBalance(double balance) {
		this.balance = balance;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "begin_time", length = 10)
	public Date getBeginTime() {
		return beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

}
