package com.langmy.terminal.common.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;
import com.langmy.terminal.common.utils.SetUtils;

/**
 * AdminssionRec generated by hbm2java
 */
@Entity
@Table(name = "adminssion_rec", catalog = "cloud")
public class AdminssionRec extends GenIdEntityImpl {

	/**
	 * 出入场记录
	 */
	private static final long serialVersionUID = 2463947092750559034L;

	private Car car; //车辆ID
	private Driveway inDriveWay; //入车道
	private Driveway outDriveway; //出车道
	private Operater inOper; //入场操作员
	private Operater outOper;//出场操作员
	private Date inTime; //入场时间
	private Date outTime; //出场时间
	private boolean freeFlag;//是否免费放行标志位
	private boolean outLiftFlag;//出场是否手动开闸放行 0:否 1：是
	private boolean inLiftFlag;//入场是否手动开闸放行 0:否 1：是
	private Integer inRecoWay; //入场识别方式
	private Integer outRecoWay; //出场识别方式
	private double amoutPay; //应付金额
	private double dctPay;//优惠金额
	private double actualPay;//实付金额
	private boolean isPay; //是否已付款
	private String inPicUrl; //入场图
	private String outPicUrl; //出场图
	private String inPicPlate;//入场车牌图片
	private String outPicPlate;//出场车牌图片
	private String inPicSafety;//入场防刮蹭图片（多张图片以";"隔开）
	private String outPicSafety;//出场防刮蹭图片（多张图片以";"隔开）
	private Set<ParkingRec> parkingRecs = new HashSet<ParkingRec>(0); //停车记录
	private Set<DelChargeRec> delChargeRecs = new HashSet<DelChargeRec>(0); //已删除收费记录
	private Set<ChargeRec> chargeRecs = new HashSet<ChargeRec>(0); //收费记录


	@Override
	public String toString() {
		return "AdminssionRec [入车道=" + inDriveWay.getName() + ", 出车道=" + outDriveway.getName() + ", 车辆ID=" + car
				+ ", 入场时间=" + inTime + ", 出场时间=" + outTime + ", 入场识别方式=" + inRecoWay + ", 出场识别方式=" + outRecoWay
				+ ", 实付金额=" + amoutPay + ", 是否已付款=" + isPay + ", 入场图=" + inPicUrl + ", 出场图=" + outPicUrl + "]";
	}

	public AdminssionRec() {
	}

	public AdminssionRec(boolean isPay) {
		this.isPay = isPay;
	}

	public AdminssionRec(Driveway inDriveWay, Driveway outDriveway, Car car, Date inTime, Date outTime,
			Integer inRecoWay, Integer outRecoWay, double amoutPay, boolean isPay, String inPicUrl, String outPicUrl,
			Set<ParkingRec> parkingRecs, Set<DelChargeRec> delChargeRecs, Set<ChargeRec> chargeRecs) {
		this.inDriveWay = inDriveWay;
		this.outDriveway = outDriveway;
		this.car = car;
		this.inTime = inTime;
		this.outTime = outTime;
		this.inRecoWay = inRecoWay;
		this.outRecoWay = outRecoWay;
		this.amoutPay = amoutPay;
		this.isPay = isPay;
		this.inPicUrl = inPicUrl;
		this.outPicUrl = outPicUrl;
		this.parkingRecs = parkingRecs;
		this.delChargeRecs = delChargeRecs;
		this.chargeRecs = chargeRecs;
	}

	public AdminssionRec(Driveway inDriveWay, Car car, Date inTime, Integer inRecoWay, String inPicUrl) {
		this.inDriveWay = inDriveWay;
		this.car = car;
		this.inTime = inTime;
		this.inRecoWay = inRecoWay;
		this.inPicUrl = inPicUrl;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "car_id")
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "in_time", length = 19)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "out_time", length = 19)
	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	@Column(name = "in_reco_way")
	public Integer getInRecoWay() {
		return this.inRecoWay;
	}

	public void setInRecoWay(Integer inRecoWay) {
		this.inRecoWay = inRecoWay;
	}

	@Column(name = "out_reco_way")
	public Integer getOutRecoWay() {
		return this.outRecoWay;
	}

	public void setOutRecoWay(Integer outRecoWay) {
		this.outRecoWay = outRecoWay;
	}

	
	@Column(name = "free_flag", nullable = false)
	public boolean isFreeFlag() {
		return this.freeFlag;
	}

	public void setFreeFlag(boolean freeFlag) {
		this.freeFlag = freeFlag;
	}

	@Column(name = "out_lift_flag", nullable = false)
	public boolean isOutLiftFlag() {
		return this.outLiftFlag;
	}

	public void setOutLiftFlag(boolean outLiftFlag) {
		this.outLiftFlag = outLiftFlag;
	}

	@Column(name = "in_lift_flag", nullable = false)
	public boolean isInLiftFlag() {
		return this.inLiftFlag;
	}

	public void setInLiftFlag(boolean inLiftFlag) {
		this.inLiftFlag = inLiftFlag;
	}

	@Column(name = "is_pay", nullable = false)
	public boolean isIsPay() {
		return this.isPay;
	}

	public void setIsPay(boolean isPay) {
		this.isPay = isPay;
	}

	@Column(name = "in_pic_url", length = 100)
	public String getInPicUrl() {
		return this.inPicUrl;
	}

	public void setInPicUrl(String inPicUrl) {
		this.inPicUrl = inPicUrl;
	}

	@Column(name = "out_pic_url", length = 100)
	public String getOutPicUrl() {
		return this.outPicUrl;
	}

	public void setOutPicUrl(String outPicUrl) {
		this.outPicUrl = outPicUrl;
	}
	
	@Column(name = "in_pic_plate", length = 100)
	public String getInPicPlate() {
		return this.inPicPlate;
	}

	public void setInPicPlate(String inPicPlate) {
		this.inPicPlate = inPicPlate;
	}

	@Column(name = "out_pic_plate", length = 100)
	public String getOutPicPlate() {
		return this.outPicPlate;
	}

	public void setOutPicPlate(String outPicPlate) {
		this.outPicPlate = outPicPlate;
	}

	@Column(name = "in_pic_safety", length = 500)
	public String getInPicSafety() {
		return this.inPicSafety;
	}

	public void setInPicSafety(String inPicSafety) {
		this.inPicSafety = inPicSafety;
	}

	@Column(name = "out_pic_safety", length = 500)
	public String getOutPicSafety() {
		return this.outPicSafety;
	}

	public void setOutPicSafety(String outPicSafety) {
		this.outPicSafety = outPicSafety;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adminssionRec")
	public Set<ParkingRec> getParkingRecs() {
		return this.parkingRecs;
	}

	public void setParkingRecs(Set<ParkingRec> parkingRecs) {
		this.parkingRecs = parkingRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adminssionRec")
	public Set<DelChargeRec> getDelChargeRecs() {
		return this.delChargeRecs;
	}

	public void setDelChargeRecs(Set<DelChargeRec> delChargeRecs) {
		this.delChargeRecs = delChargeRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "adminssionRec")
	public Set<ChargeRec> getChargeRecs() {
		return this.chargeRecs;
	}

	public void setChargeRecs(Set<ChargeRec> chargeRecs) {
		this.chargeRecs = chargeRecs;
	}

	@Transient
	public List<ParkingRec> getParkingRecList() {
		return SetUtils.convertList(parkingRecs);
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entrance_id")
	public Driveway getInDriveWay() {
		return inDriveWay;
	}

	public void setInDriveWay(Driveway inDriveWay) {
		this.inDriveWay = inDriveWay;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exit_id")
	public Driveway getOutDriveway() {
		return outDriveway;
	}

	public void setOutDriveway(Driveway outDriveway) {
		this.outDriveway = outDriveway;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "in_oper_id")
	public Operater getInOper() {
		return inOper;
	}

	public void setInOper(Operater inOper) {
		this.inOper = inOper;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "out_oper_id")
	public Operater getOutOper() {
		return outOper;
	}

	public void setOutOper(Operater outOper) {
		this.outOper = outOper;
	}

	@Column(name = "amout_pay", precision = 10, nullable = false)
	public double getAmoutPay() {
		return amoutPay;
	}

	public void setAmoutPay(double amoutPay) {
		this.amoutPay = amoutPay;
	}
	@Column(name = "dct_pay", precision = 10, nullable = false)
	public double getDctPay() {
		return dctPay;
	}

	public void setDctPay(double dctPay) {
		this.dctPay = dctPay;
	}
	@Column(name = "actual_pay", precision = 10, nullable = false)
	public double getActualPay() {
		return actualPay;
	}

	public void setActualPay(double actualPay) {
		this.actualPay = actualPay;
	}

}
