package com.langmy.terminal.common.entity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * AnchorGroup generated by hbm2java
 */
@Entity
@Table(name = "anchor_group", catalog = "cloud")
public class AnchorCharge extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4142810659578186897L;
	private String monthPay; // 收费组编号
	private String quarterPay; // 收费组名称
	private String yearPay; // 收费组描述
	private boolean delFlag; // 删除标志

	@Column(name = "month_pay", nullable = false, precision = 10)
	public String getMonthPay() {
		return monthPay;
	}

	public void setMonthPay(String monthPay) {
		this.monthPay = monthPay;
	}

	@Column(name = "quarter_pay", nullable = false, precision = 10)
	public String getQuarterPay() {
		return quarterPay;
	}

	public void setQuarterPay(String quarterPay) {
		this.quarterPay = quarterPay;
	}

	@Column(name = "year_pay", nullable = false, precision = 10)
	public String getYearPay() {
		return yearPay;
	}

	public void setYearPay(String yearPay) {
		this.yearPay = yearPay;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

	@Override
	public String toString() {
		return "AnchorGroup [包月=" + monthPay + ", 包季=" + quarterPay + ", 包年="
				+ yearPay + "]";
	}

}
