package com.langmy.terminal.common.entity;

// Generated 2015-2-3 18:18:41 by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.google.common.collect.Lists;
import com.langmy.terminal.common.persistence.DetailRule;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * AnchorRent generated by hbm2java
 */
@Entity
@Table(name = "anchor_rent", catalog = "cloud")
public class AnchorRent extends GenIdEntityImpl implements DetailRule {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3165234100568881853L;
	private String anchorRentId; //长期收费编号
	private String name; //名称
	private double fee; //费用
	private int month; //月份
	private Double addFee; //附加费用
	private boolean delFlag; //删除标志位
	private List<AnchorCharge> GAnchorRents = Lists.newArrayList();
	
	public AnchorRent() {
	}

	public AnchorRent(String anchorRentId, String name, double fee, int month) {
		this.anchorRentId = anchorRentId;
		this.name = name;
		this.fee = fee;
		this.month = month;
	}

	public AnchorRent(String anchorRentId, String name, double fee, int month, Double addFee,
			List<AnchorCharge> GAnchorRents) {
		this.anchorRentId = anchorRentId;
		this.name = name;
		this.fee = fee;
		this.month = month;
		this.addFee = addFee;
		this.GAnchorRents = GAnchorRents;
	}

	@Column(name = "anchor_rent_id", nullable = false, length = 30)
	public String getAnchorRentId() {
		return this.anchorRentId;
	}

	public void setAnchorRentId(String anchorRentId) {
		this.anchorRentId = anchorRentId;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "fee", nullable = false, precision = 10)
	public double getFee() {
		return this.fee;
	}

	public void setFee(double fee) {
		this.fee = fee;
	}

	@Column(name = "month", nullable = false)
	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	@Column(name = "add_fee", precision = 10)
	public Double getAddFee() {
		return this.addFee;
	}

	public void setAddFee(Double addFee) {
		this.addFee = addFee;
	}

	@JSONField(serialize = false)
	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "g_anchor_rent", catalog = "cloud", joinColumns = { @JoinColumn(name = "anchor_rent_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "group_id", nullable = false, updatable = false) })
	public List<AnchorCharge> getGAnchorRents() {
		return this.GAnchorRents;
	}

	public void setGAnchorRents(List<AnchorCharge> GAnchorRents) {
		this.GAnchorRents = GAnchorRents;
	}

	@Override
	@Transient
	public String getRuleId() {
		return anchorRentId;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "长期收费 [长期收费编号=" + anchorRentId + ", 名称=" + name + ", 费用=" + fee + ", 月份=" + month
				+ ", 附加费用=" + addFee + ", 删除标志位=" + delFlag + "]";
	}

}
