package com.langmy.terminal.common.entity;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.google.common.collect.Lists;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "cloud", uniqueConstraints = @UniqueConstraint(columnNames = "area_id"))
public class Area extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8159580488547398477L;
	private String areaId; //区域编号
	private String name; //区域名称
	private String posit; //区域位置
	private boolean delFlag; //删除标志位
	private Set<PSp> PSps = new HashSet<PSp>(0); 
	private List<LedScreen> ledScreens = Lists.newArrayList();

	@Override
	public String toString() {
		return "区域[ID=" + id + ", 区域编号=" + areaId + ", 区域名称=" + name
				+ ", 区域位置=" + posit + "]";
	}

	public Area() {
	}

	public Area(String areaId) {
		this.areaId = areaId;
	}

	public Area(String areaId, String name, String posit, Set<PSp> PSps) {
		this.areaId = areaId;
		this.name = name;
		this.posit = posit;
		this.PSps = PSps;
	}

	@Column(name = "area_id", unique = true, nullable = false, length = 20)
	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "posit", length = 30)
	public String getPosit() {
		return this.posit;
	}

	public void setPosit(String posit) {
		this.posit = posit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<PSp> getPSps() {
		return this.PSps;
	}

	public void setPSps(Set<PSp> PSps) {
		this.PSps = PSps;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "screen_area", catalog = "cloud", joinColumns = { @JoinColumn(name = "area_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "led_screen_id", nullable = false, updatable = false) })
	public List<LedScreen> getLedScreens() {
		return ledScreens;
	}

	public void setLedScreens(List<LedScreen> ledScreens) {
		this.ledScreens = ledScreens;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return delFlag;
	}
	
	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

}
