package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.google.common.collect.Lists;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * Bayonet generated by hbm2java
 */
@Entity
@Table(name = "bayonet", catalog = "cloud", uniqueConstraints = @UniqueConstraint(columnNames = "bayonet_id"))
public class Bayonet extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5704901654031403591L;
	private String bayonetId; //出入口编号
	private String name; //出入口名称
	private String posit; //出入口位置
	private boolean delFlag; //删除标志
	private Park park; //停车场

	private List<Driveway> driveway = Lists.newArrayList();
	private Set<DelAdmissionRec> delParkingRecsForExitId = new HashSet<DelAdmissionRec>(
			0);
	private Set<DelAdmissionRec> delParkingRecsForEntranceId = new HashSet<DelAdmissionRec>(
			0);
	private Set<OperLiftRec> operLiftRecs = new HashSet<OperLiftRec>(0);

	public Bayonet() {
	}

	public Bayonet(String bayonetId, String name,  String posit, 
			Set<OperLiftRec> operLiftRecs,
			Set<AdminssionRec> adminssionRecsForEntranceId,
			Set<AdminssionRec> adminssionRecsForExitId) {
		this.bayonetId = bayonetId;
		this.name = name;
		this.posit = posit;
		this.operLiftRecs = operLiftRecs;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "park_id")
	public Park getPark() {
		return this.park;
	}

	public void setPark(Park park) {
		this.park = park;
	}
	
	@Column(name = "bayonet_id", unique = true, length = 20)
	public String getBayonetId() {
		return this.bayonetId;
	}

	public void setBayonetId(String bayonetId) {
		this.bayonetId = bayonetId;
	}

	@Column(name = "name", length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}


	@Column(name = "posit", length = 30)
	public String getPosit() {
		return this.posit;
	}

	public void setPosit(String posit) {
		this.posit = posit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bayonetByExitId")
	public Set<DelAdmissionRec> getDelParkingRecsForExitId() {
		return this.delParkingRecsForExitId;
	}

	public void setDelParkingRecsForExitId(
			Set<DelAdmissionRec> delParkingRecsForExitId) {
		this.delParkingRecsForExitId = delParkingRecsForExitId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bayonetByEntranceId")
	public Set<DelAdmissionRec> getDelParkingRecsForEntranceId() {
		return this.delParkingRecsForEntranceId;
	}

	public void setDelParkingRecsForEntranceId(
			Set<DelAdmissionRec> delParkingRecsForEntranceId) {
		this.delParkingRecsForEntranceId = delParkingRecsForEntranceId;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bayonet")
	public Set<OperLiftRec> getOperLiftRecs() {
		return this.operLiftRecs;
	}

	public void setOperLiftRecs(Set<OperLiftRec> operLiftRecs) {
		this.operLiftRecs = operLiftRecs;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}
	

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "bayonet")
	public List<Driveway> getDriveway() {
		return driveway;
	}

	/**
	 * @param driveway the driveway to set
	 */
	public void setDriveway(List<Driveway> driveway) {
		this.driveway = driveway;
	}

}
