package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * Blacklist generated by hbm2java
 */
@Entity
@Table(name = "blacklist", catalog = "cloud", uniqueConstraints = @UniqueConstraint(columnNames = "blacklist_id"))
public class Blacklist extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4436127753825145711L;
	private User user;  //客户名
	private String blacklistId; //黑名单编号
	private String listReason; //列入黑名单原因
	private Date listTime; //列入时间
	private Date endTime; //到期时间
	private Boolean isEffect; //是否生效
	private Double needFee; //应缴金额
	private String removeWay; //解除黑名单方式
	private boolean inFlag; //是否允许进场

	@Override
	public String toString() {
		return "Blacklist [客户名=" + user + ", 黑名单ID=" + blacklistId
				+ ", 列入黑名单原因=" + listReason + ", 列入时间=" + listTime + ", 到期时间="
				+ endTime + ", 是否生效=" + isEffect + ", 应缴金额=" + needFee
				+ ", 解除黑名单方式=" + removeWay + "]";
	}

	public Blacklist() {
	}

	public Blacklist(User user, String blacklistId, String listReason,
			Date listTime, Date endTime, Boolean isEffect, Double needFee,
			String removeWay, boolean inFlag) {
		this.user = user;
		this.blacklistId = blacklistId;
		this.listReason = listReason;
		this.listTime = listTime;
		this.endTime = endTime;
		this.isEffect = isEffect;
		this.needFee = needFee;
		this.removeWay = removeWay;
		this.inFlag = inFlag;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "blacklist_id", unique = true, length = 20)
	public String getBlacklistId() {
		return this.blacklistId;
	}

	public void setBlacklistId(String blacklistId) {
		this.blacklistId = blacklistId;
	}

	@Column(name = "list_reason", length = 50)
	public String getListReason() {
		return this.listReason;
	}

	public void setListReason(String listReason) {
		this.listReason = listReason;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "list_time", length = 19)
	public Date getListTime() {
		return this.listTime;
	}

	public void setListTime(Date listTime) {
		this.listTime = listTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 19)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "is_effect")
	public Boolean getIsEffect() {
		return this.isEffect;
	}

	public void setIsEffect(Boolean isEffect) {
		this.isEffect = isEffect;
	}

	@Column(name = "need_fee", precision = 10)
	public Double getNeedFee() {
		return this.needFee;
	}

	public void setNeedFee(Double needFee) {
		this.needFee = needFee;
	}

	@Column(name = "remove_way", length = 20)
	public String getRemoveWay() {
		return this.removeWay;
	}

	public void setRemoveWay(String removeWay) {
		this.removeWay = removeWay;
	}

	@Column(name = "in_flag", nullable = false)
	public boolean isInFlag() {
		return this.inFlag;
	}

	public void setInFlag(boolean inFlag) {
		this.inFlag = inFlag;
	}

}
