package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.google.common.collect.Lists;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * Car generated by hbm2java
 */
@Entity
@Table(name = "car", catalog = "cloud", uniqueConstraints = @UniqueConstraint(columnNames = "license_plate"))
public class Car extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3706380366805894735L;
	private User user; // 客户名
	private String licensePlate; // 车牌号
	private String type; // 车牌类型
	private String carColor; // 颜色
	private String carModel; // 型号
	private int carType; // 车辆类型
	private boolean delFlag; // 删除标志位
	private Set<PSp> PSps = new HashSet<PSp>(0); // 车位
	private List<DelParkingRec> delParkingRecs = Lists.newArrayList(); // 删除停车记录表
	private Set<ParkingRec> parkingRecs = new HashSet<ParkingRec>(0); // 停车记录表
	private Set<DelAdmissionRec> delAdmissionRecs = new HashSet<DelAdmissionRec>(
			0); // 已删除出入场记录
	private Set<AdminssionRec> adminssionRecs = new HashSet<AdminssionRec>(0); // 出入场记录

	@Override
	public String toString() {
		return "Car [客户名=" + user + ", 车牌号=" + licensePlate + ", 车牌类型=" + type
				+ ", 颜色=" + carColor + ", 型号=" + carModel + ", 车辆类型=" + carType
				+ "]";
	}

	public Car() {
	}

	public Car(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	public Car(User user, String licensePlate, String type, String carColor,
			String carModel, int carType) {
		this.user = user;
		this.licensePlate = licensePlate;
		this.type = type;
		this.carColor = carColor;
		this.carModel = carModel;
		this.carType = carType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id")
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "license_plate", nullable = false, length = 10)
	public String getLicensePlate() {
		return this.licensePlate;
	}

	public void setLicensePlate(String licensePlate) {
		this.licensePlate = licensePlate;
	}

	@Column(name = "type", length = 10)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "car_color", length = 10)
	public String getCarColor() {
		return this.carColor;
	}

	public void setCarColor(String carColor) {
		this.carColor = carColor;
	}

	@Column(name = "car_model", length = 10)
	public String getCarModel() {
		return this.carModel;
	}

	public void setCarModel(String carModel) {
		this.carModel = carModel;
	}

	@Column(name = "car_type", length = 2)
	public Integer getCarType() {
		return this.carType;
	}

	public void setCarType(int carType) {
		this.carType = carType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<PSp> getPSps() {
		return this.PSps;
	}

	public void setPSps(Set<PSp> PSps) {
		this.PSps = PSps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<ParkingRec> getParkingRecs() {
		return this.parkingRecs;
	}

	public void setParkingRecs(Set<ParkingRec> parkingRecs) {
		this.parkingRecs = parkingRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<AdminssionRec> getAdminssionRecs() {
		return this.adminssionRecs;
	}

	public void setAdminssionRecs(Set<AdminssionRec> adminssionRecs) {
		this.adminssionRecs = adminssionRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public List<DelParkingRec> getDelParkingRecs() {
		return delParkingRecs;
	}

	public void setDelParkingRecs(List<DelParkingRec> delParkingRecs) {
		this.delParkingRecs = delParkingRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "car")
	public Set<DelAdmissionRec> getDelAdmissionRecs() {
		return delAdmissionRecs;
	}

	public void setDelAdmissionRecs(Set<DelAdmissionRec> delAdmissionRecs) {
		this.delAdmissionRecs = delAdmissionRecs;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

}
