package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * CarType generated by hbm2java
 */
@Entity
@Table(name = "car_type", catalog = "cloud")
public class CarType extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5620786602797591522L;
	private Integer type; //类型
	private Boolean isFree; //车牌是否免费放行
	private String typeName; //车牌类型名称
	private String color; //车辆颜色
	private String model; //车辆型号
	private boolean delFlag; //删除标志位

	@Override
	public String toString() {
		return "CarType [类型=" + type + ", 车牌是否免费放行=" + isFree + ", 车牌类型名称="
				+ typeName + ", 车辆颜色=" + color + ", 车辆型号=" + model + "]";
	}

	public CarType() {
	}

	public CarType(Integer type, Boolean isFree, String typeName, String color,
			String model) {
		this.type = type;
		this.isFree = isFree;
		this.typeName = typeName;
		this.color = color;
		this.model = model;
	}

	@Column(name = "type")
	public Integer getType() {
		return this.type;
	}

	public void setType(Integer type) {
		this.type = type;
	}

	@Column(name = "is_free")
	public Boolean getIsFree() {
		return this.isFree;
	}

	public void setIsFree(Boolean isFree) {
		this.isFree = isFree;
	}

	@Column(name = "type_name", length = 20)
	public String getTypeName() {
		return this.typeName;
	}

	public void setTypeName(String typeName) {
		this.typeName = typeName;
	}

	@Column(name = "color", length = 20)
	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

	@Column(name = "model", length = 20)
	public String getModel() {
		return this.model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

}
