package com.langmy.terminal.common.entity;

// Generated 2015-2-5 10:48:07 by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.google.common.collect.Lists;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;
import com.langmy.terminal.common.persistence.RuleI;

/**
 * ChargeRule generated by hbm2java
 */
@Entity
@Table(name = "charge_rule", catalog = "cloud")
public class ChargeRule extends GenIdEntityImpl implements RuleI {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1470247526178101023L;
	private String rentRuleId; //车位租赁规则编号
	private String ruleName; //租赁规则名称
	private Integer baseRuleId; //base_rule_id
	private Integer rentType; //收费类型  0：计时 1：计次 2：长期 3:免费放行
	private boolean delFlag; //删除标志位
	private List<UserPSp> userPSps = Lists.newArrayList(); //用户车位
	private List<UGChargeRule> UGChargeRules = Lists.newArrayList(); //客户组收费规则
	private List<RechargeRec> rechargeRecs = Lists.newArrayList(); //充值记录
	private List<ChargeRec> chargeRecs = Lists.newArrayList(); //收费记录

	public ChargeRule() {
	}

	public ChargeRule(ChargeRule chargeRule) {
		this.rentRuleId = chargeRule.getRentRuleId();
		this.ruleName = chargeRule.getRuleName();
		this.baseRuleId = chargeRule.getBaseRuleId();
		this.rentType = chargeRule.getRentType();
	}

	public ChargeRule(String rentRuleId, String ruleName, Integer baseRuleId,
			Integer rentType) {
		this.rentRuleId = rentRuleId;
		this.ruleName = ruleName;
		this.baseRuleId = baseRuleId;
		this.rentType = rentType;
	}

	@Column(name = "rent_rule_id", nullable = false, length = 30)
	public String getRentRuleId() {
		return this.rentRuleId;
	}

	public void setRentRuleId(String rentRuleId) {
		this.rentRuleId = rentRuleId;
	}

	@Column(name = "rule_name", nullable = false, length = 30)
	public String getRuleName() {
		return this.ruleName;
	}

	public void setRuleName(String ruleName) {
		this.ruleName = ruleName;
	}


	@Column(name = "base_rule_id")
	public Integer getBaseRuleId() {
		return this.baseRuleId;
	}

	public void setBaseRuleId(Integer baseRuleId) {
		this.baseRuleId = baseRuleId;
	}

	@Column(name = "rent_type")
	public Integer getRentType() {
		return this.rentType;
	}

	public void setRentType(Integer rentType) {
		this.rentType = rentType;
	}

	@JSONField(serialize = false)	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeRule")
	public List<UserPSp> getUserPSps() {
		return this.userPSps;
	}

	public void setUserPSps(List<UserPSp> userPSps) {
		this.userPSps = userPSps;
	}
	@JSONField(serialize = false)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeRule")
	public List<UGChargeRule> getUGChargeRules() {
		return this.UGChargeRules;
	}

	public void setUGChargeRules(List<UGChargeRule> UGChargeRules) {
		this.UGChargeRules = UGChargeRules;
	}
	@JSONField(serialize = false)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeRule")
	public List<RechargeRec> getRechargeRecs() {
		return this.rechargeRecs;
	}

	public void setRechargeRecs(List<RechargeRec> rechargeRecs) {
		this.rechargeRecs = rechargeRecs;
	}

	@Override
	public String toString() {
		return "收费规则 [编号=" + rentRuleId + ", 名称=" + ruleName  + ", baseRuleId=" + baseRuleId + ", 租用类型="
				+ rentType+ "id=" + id + "]";
	}

	@Transient
	public String getName() {
		return ruleName;
	}

	@Override
	@Transient
	public String getRuleId() {
		return rentRuleId;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

	@JSONField(serialize = false)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "chargeRule")
	public List<ChargeRec> getChargeRecs() {
		return chargeRecs;
	}

	public void setChargeRecs(List<ChargeRec> chargeRecs) {
		this.chargeRecs = chargeRecs;
	}
	
	@Transient
	public List<UGroup> getUGroups(){
		List<UGroup> uGroups = Lists.newArrayList();
		List<UGChargeRule> uGChargeRules = getUGChargeRules();
		for(UGChargeRule u:uGChargeRules){
			UGroup uGroup = u.getUGroup();
			uGroups.add(uGroup);
		}
		return uGroups;
	}


}
