package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * ContactWay generated by hbm2java
 */
@Entity
@Table(name = "contact_way", catalog = "cloud")
public class ContactWay extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5293865371223016805L;
	private int contactId; //外键
	private int type; //类型
	private String company; //单位名称
	private String mobilePhone; //手机号
	private String tel; //固定电话
	private String qq; //QQ
	private String zipCode; //邮编
	private String fax; //传真
	private String email; //EMail
	private String var1; //预留字段1

	@Override
	public String toString() {
		return "ContactWay [外键=" + contactId + ", 类型=" + type + ", 单位名称="
				+ company + ", 手机号=" + mobilePhone + ", 固定电话=" + tel + ", qq号="
				+ qq + ", 邮编=" + zipCode + ", 传真=" + fax + ", 邮箱=" + email
				+ "]";
	}

	public ContactWay() {
	}

	public ContactWay(int contactId, int type) {
		this.contactId = contactId;
		this.type = type;
	}

	public ContactWay(int contactId, int type, String company,
			String mobilePhone, String tel, String qq, String zipCode,
			String fax, String email, String var1) {
		this.contactId = contactId;
		this.type = type;
		this.company = company;
		this.mobilePhone = mobilePhone;
		this.tel = tel;
		this.qq = qq;
		this.zipCode = zipCode;
		this.fax = fax;
		this.email = email;
		this.var1 = var1;
	}

	@Column(name = "contact_id", nullable = false)
	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Column(name = "company", length = 50)
	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	@Column(name = "mobile_phone", length = 11)
	public String getMobilePhone() {
		return this.mobilePhone;
	}

	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	@Column(name = "tel", length = 30)
	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	@Column(name = "qq", length = 20)
	public String getQq() {
		return this.qq;
	}

	public void setQq(String qq) {
		this.qq = qq;
	}

	@Column(name = "zip_code", length = 6)
	public String getZipCode() {
		return this.zipCode;
	}

	public void setZipCode(String zipCode) {
		this.zipCode = zipCode;
	}

	@Column(name = "fax", length = 30)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "email", length = 30)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "var1", length = 20)
	public String getVar1() {
		return this.var1;
	}

	public void setVar1(String var1) {
		this.var1 = var1;
	}

}
