package com.langmy.terminal.common.entity;

// Generated 2015-2-5 11:56:03 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.google.common.collect.Lists;
import com.langmy.terminal.common.config.Constant;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * DctRule generated by hbm2java
 */
@Entity
@Table(name = "dct_rule", catalog = "cloud")
public class DctRule extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4836686886183990009L;
	private String dctId; // 优惠规则编号
	private String dctName; // 优惠规则名称
	private int type; // 类型
	private Date beginTime;// 开始时间
	private Date endTime;// 结束时间
	private Integer weekendType;// 双休日类型
	private Double dctPer;// 优惠金额或者折扣
	private Integer dctType;// 优惠类型(0:减免金额;1:打折;2:全免)
	private boolean delFlag;// 删除标志位

	private List<DctRuleGroup> dctRuleGroups = Lists.newArrayList(); // 对应的优惠规则组

	public DctRule() {
	}

	public DctRule(String dctId, String dctName, int type) {
		this.dctId = dctId;
		this.dctName = dctName;
		this.type = type;
	}

	public DctRule(String dctId, String dctName, int type, Date beginTime,
			Date endTime, Integer weekendType, Date beginDate, Date endDate,
			Double dctPer) {
		this.dctId = dctId;
		this.dctName = dctName;
		this.type = type;
		this.beginTime = beginTime;
		this.endTime = endTime;
		this.weekendType = weekendType;
		this.dctPer = dctPer;
	}

	@Column(name = "dct_id", nullable = false, length = 30)
	public String getDctId() {
		return this.dctId;
	}

	public void setDctId(String dctId) {
		this.dctId = dctId;
	}

	@Column(name = "dct_name", nullable = false, length = 30)
	public String getDctName() {
		return this.dctName;
	}

	public void setDctName(String dctName) {
		this.dctName = dctName;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "begin_time", length = 8)
	public Date getBeginTime() {
		return this.beginTime;
	}

	public void setBeginTime(Date beginTime) {
		this.beginTime = beginTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_time", length = 8)
	public Date getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Date endTime) {
		this.endTime = endTime;
	}

	@Column(name = "weekend_type")
	public Integer getWeekendType() {
		return this.weekendType;
	}

	public void setWeekendType(Integer weekendType) {
		this.weekendType = weekendType;
	}

	@Column(name = "dct_per", precision = 5)
	public Double getDctPer() {
		return this.dctPer;
	}

	public void setDctPer(Double dctPer) {
		this.dctPer = dctPer;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "dct_type")
	public Integer getDctType() {
		return dctType;
	}

	public void setDctType(Integer dctType) {
		this.dctType = dctType;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "rule_dct_group", catalog = "cloud", joinColumns = { @JoinColumn(name = "dct_rule_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "dct_group_id", nullable = false, updatable = false) })
	public List<DctRuleGroup> getDctRuleGroups() {
		return dctRuleGroups;
	}

	public void setDctRuleGroups(List<DctRuleGroup> dctRuleGroups) {
		this.dctRuleGroups = dctRuleGroups;
	}

	/*
	 * (non-Javadoc)
	 * 
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		String weekendStr = "";
		if (weekendType == Constant.DctRuleType.WEEKEND_SAT.getValue())
			weekendStr = "周六";
		else if (weekendType == Constant.DctRuleType.WEEKEND_SUN.getValue())
			weekendStr = "周日";
		else if (weekendType == Constant.DctRuleType.WEEKEND_BOTH.getValue())
			weekendStr = "周六或周日";
		String typeStr = "";
		if (type == Constant.DctRuleType.TIME.getValue())
			typeStr = "规定时间";
		else if (type == Constant.DctRuleType.BIRTH.getValue())
			typeStr = "生日";
		else if (type == Constant.DctRuleType.WEEKEND.getValue())
			typeStr = "双休日";
		else if (type == Constant.DctRuleType.HOLIDAY.getValue())
			typeStr = "节假日";
		return "优惠规则 [优惠规则编号=" + dctId + ", 优惠规则名称=" + dctName + ", 优惠规则类型="
				+ typeStr + ", 开始时间=" + beginTime + ", 结束时间=" + endTime
				+ ", 双休日类型=" + weekendStr + ",优惠百分比/优惠金额=" + dctPer + ", 优惠类型="
				+ dctType + ", 删除标志位=" + delFlag + "]";
	}

}
