package com.langmy.terminal.common.entity;

// Generated 2015-5-4 12:43:51 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * DctRec generated by hbm2java
 */
@Entity
@Table(name = "dct_rec", catalog = "cloud")
public class DctRec implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5768778244428286741L;
	private Integer id;
	private ChargeRec chargeRec; //收费记录
	private String reason; //优惠原因
	private double dctPer; //优惠折扣

	public DctRec() {
	}

	public DctRec(ChargeRec chargeRec, String reason, double dctPer) {
		this.chargeRec = chargeRec;
		this.reason = reason;
		this.dctPer = dctPer;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "charge_rec_id", nullable = false)
	public ChargeRec getChargeRec() {
		return this.chargeRec;
	}

	public void setChargeRec(ChargeRec chargeRec) {
		this.chargeRec = chargeRec;
	}

	@Column(name = "reason", nullable = false, length = 100)
	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

	@Column(name = "dct_per", nullable = false, precision = 5)
	public double getDctPer() {
		return this.dctPer;
	}

	public void setDctPer(double dctPer) {
		this.dctPer = dctPer;
	}

}
