package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.alibaba.fastjson.annotation.JSONField;
import com.google.common.collect.Lists;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;
import com.langmy.terminal.common.persistence.RuleI;

/**
 * DctRuleGroup generated by hbm2java
 */
@Entity
@Table(name = "dct_rule_group", catalog = "cloud")
public class DctRuleGroup extends GenIdEntityImpl implements RuleI {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5294882286972689590L;
	private String groupId; //优惠规则组ID
	private String name; //优惠规则组名称
	private String describion; //规则组描述
	private boolean delFlag; //删除标志位
	
	private List<DelChargeRec> delChargeRecs = Lists.newArrayList();
	private List<UGroup> UGroups = Lists.newArrayList();
	private List<ChargeRec> chargeRecs = Lists.newArrayList();
	private List<DctRule> dctRules = Lists.newArrayList();


	public DctRuleGroup() {
	}

	public DctRuleGroup(String groupId, String name, String describion) {
		this.groupId = groupId;
		this.name = name;
		this.describion = describion;
	}


	public DctRuleGroup(String groupId, String name, String describion,
			 List<DelChargeRec> delChargeRecs,
			List<UGroup> UGroups, List<ChargeRec> chargeRecs) {
		this.groupId = groupId;
		this.name = name;
		this.describion = describion;
		this.delChargeRecs = delChargeRecs;
		this.UGroups = UGroups;
		this.chargeRecs = chargeRecs;
	}

	public DctRuleGroup(DctRuleGroup group) {
		this.groupId = group.getGroupId();
		this.name = group.getName();
		this.describion = group.getDescribion();
	}

	@Column(name = "group_id", nullable = false, length = 30)
	public String getGroupId() {
		return this.groupId;
	}

	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}

	@Column(name = "name", nullable = false, length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "describion", length = 255)
	public String getDescribion() {
		return this.describion;
	}

	public void setDescribion(String describion) {
		this.describion = describion;
	}

	@JSONField(serialize = false)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dctRuleGroup")
	public List<DelChargeRec> getDelChargeRecs() {
		return this.delChargeRecs;
	}

	public void setDelChargeRecs(List<DelChargeRec> delChargeRecs) {
		this.delChargeRecs = delChargeRecs;
	}

	@JSONField(serialize = false)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dctRuleGroup")
	public List<UGroup> getUGroups() {
		return this.UGroups;
	}

	public void setUGroups(List<UGroup> UGroups) {
		this.UGroups = UGroups;
	}

	@JSONField(serialize = false)
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "dctRuleGroup")
	public List<ChargeRec> getChargeRecs() {
		return this.chargeRecs;
	}

	public void setChargeRecs(List<ChargeRec> chargeRecs) {
		this.chargeRecs = chargeRecs;
	}

	@Override
	public String toString() {

		return "优惠规则组 [ID=" + id + "优惠规则组编号=" + groupId + ", 名称=" + name
				+ ", 描述=" + describion;
	}

	@Override
	@Transient
	public String getRuleId() {
		return groupId;
	}
	
	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

	@JSONField(serialize = false)
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "rule_dct_group", catalog = "cloud", joinColumns = { @JoinColumn(name = "dct_group_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "dct_rule_id", nullable = false, updatable = false) })
	public List<DctRule> getDctRules() {
		return dctRules;
	}

	public void setDctRules(List<DctRule> dctRules) {
		this.dctRules = dctRules;
	}
}
