package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.langmy.terminal.common.persistence.IdEntityImpl;

/**
 * DelParkingRec generated by hbm2java
 */
@Entity
@Table(name = "del_admission_rec", catalog = "cloud")
public class DelAdmissionRec extends IdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1254025051907790497L;
	private Bayonet bayonetByExitId; //出口
	private Bayonet bayonetByEntranceId; //入口
	private Car car; //车辆
	private Date inTime; //入场时间
	private Date outTime; //出场时间
	private Integer inRecoWay; //入场识别方式
	private Integer outRecoWay; //出场识别方式
	private Double fee; //应付金额
	private boolean isPay; //是否已付款
	private String inPicUrl; //入场图片
	private String outPicUrl; //出场图片
	private Date delTime; //删除时间

	@Override
	public String toString() {
		return "DelAdmissionRec [出口=" + bayonetByExitId + ", 入口="
				+ bayonetByEntranceId + ", 车辆=" + car + ", 入场时间=" + inTime
				+ ", 出场时间=" + outTime + ", 入场识别方式=" + inRecoWay + ", 出场识别方式="
				+ outRecoWay + ", 应实付金额=" + fee + ", 是否已付款=" + isPay
				+ ", 入场图片=" + inPicUrl + ", 出场图片=" + outPicUrl + ", 删除时间="
				+ delTime + "]";
	}

	public DelAdmissionRec() {
	}

	public DelAdmissionRec(Car car, boolean isPay, Date delTime) {
		this.car = car;
		this.isPay = isPay;
		this.delTime = delTime;
	}

	public DelAdmissionRec(Bayonet bayonetByExitId,
			Bayonet bayonetByEntranceId, Car car, Date inTime, Date outTime,
			Integer inRecoWay, Integer outRecoWay, Double fee, boolean isPay,
			String inPicUrl, String outPicUrl, Date delTime) {
		this.bayonetByExitId = bayonetByExitId;
		this.bayonetByEntranceId = bayonetByEntranceId;
		this.car = car;
		this.inTime = inTime;
		this.outTime = outTime;
		this.inRecoWay = inRecoWay;
		this.outRecoWay = outRecoWay;
		this.fee = fee;
		this.isPay = isPay;
		this.inPicUrl = inPicUrl;
		this.outPicUrl = outPicUrl;
		this.delTime = delTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "exit_id")
	public Bayonet getBayonetByExitId() {
		return this.bayonetByExitId;
	}

	public void setBayonetByExitId(Bayonet bayonetByExitId) {
		this.bayonetByExitId = bayonetByExitId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "entrance_id")
	public Bayonet getBayonetByEntranceId() {
		return this.bayonetByEntranceId;
	}

	public void setBayonetByEntranceId(Bayonet bayonetByEntranceId) {
		this.bayonetByEntranceId = bayonetByEntranceId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "car_id", nullable = false)
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "in_time", length = 19)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "out_time", length = 19)
	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	@Column(name = "in_reco_way")
	public Integer getInRecoWay() {
		return this.inRecoWay;
	}

	public void setInRecoWay(Integer inRecoWay) {
		this.inRecoWay = inRecoWay;
	}

	@Column(name = "out_reco_way")
	public Integer getOutRecoWay() {
		return this.outRecoWay;
	}

	public void setOutRecoWay(Integer outRecoWay) {
		this.outRecoWay = outRecoWay;
	}

	@Column(name = "fee", precision = 10)
	public Double getFee() {
		return this.fee;
	}

	public void setFee(Double fee) {
		this.fee = fee;
	}

	@Column(name = "is_pay", nullable = false)
	public boolean isIsPay() {
		return this.isPay;
	}

	public void setIsPay(boolean isPay) {
		this.isPay = isPay;
	}

	@Column(name = "in_pic_url", length = 100)
	public String getInPicUrl() {
		return this.inPicUrl;
	}

	public void setInPicUrl(String inPicUrl) {
		this.inPicUrl = inPicUrl;
	}

	@Column(name = "out_pic_url", length = 100)
	public String getOutPicUrl() {
		return this.outPicUrl;
	}

	public void setOutPicUrl(String outPicUrl) {
		this.outPicUrl = outPicUrl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "del_time", nullable = false, length = 19)
	public Date getDelTime() {
		return this.delTime;
	}

	public void setDelTime(Date delTime) {
		this.delTime = delTime;
	}

}
