package com.langmy.terminal.common.entity;

// Generated 2015-2-5 11:56:03 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.langmy.terminal.common.persistence.IdEntityImpl;

/**
 * DelChargeRec generated by hbm2java
 */
@Entity
@Table(name = "del_charge_rec", catalog = "cloud")
public class DelChargeRec extends IdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4186026988511291258L;
	private AdminssionRec adminssionRec; //出入场记录
	private DctRuleGroup dctRuleGroup; //优惠规则组
	private Operater operater; //操作员
	private int payType; //付款方式
	private Date payTime; //付款时间
	private double amoutPay; //应付金额
	private double dctPay; //优惠金额
	private double actualPay; //实付金额
	private Date delTime; //删除时间
	
	@PrePersist
	public void pre() {
		this.delTime = new Date();
	}

	public DelChargeRec() {
	}

	public DelChargeRec(AdminssionRec adminssionRec, int payType, Date payTime,
			double amoutPay, double dctPay, double actualPay, Date delTime) {
		this.adminssionRec = adminssionRec;
		this.payType = payType;
		this.payTime = payTime;
		this.amoutPay = amoutPay;
		this.dctPay = dctPay;
		this.actualPay = actualPay;
		this.delTime = delTime;
	}

	public DelChargeRec(AdminssionRec adminssionRec, DctRuleGroup dctRuleGroup,
			Operater operater, int payType, Date payTime, double amoutPay,
			double dctPay, double actualPay, Date delTime,
			List<DctRule> effectDctRules) {
		this.adminssionRec = adminssionRec;
		this.dctRuleGroup = dctRuleGroup;
		this.operater = operater;
		this.payType = payType;
		this.payTime = payTime;
		this.amoutPay = amoutPay;
		this.dctPay = dctPay;
		this.actualPay = actualPay;
		this.delTime = delTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "admission_rec_id", nullable = false)
	public AdminssionRec getAdminssionRec() {
		return this.adminssionRec;
	}

	public void setAdminssionRec(AdminssionRec adminssionRec) {
		this.adminssionRec = adminssionRec;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dct_group_id")
	public DctRuleGroup getDctRuleGroup() {
		return this.dctRuleGroup;
	}

	public void setDctRuleGroup(DctRuleGroup dctRuleGroup) {
		this.dctRuleGroup = dctRuleGroup;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oper_id")
	public Operater getOperater() {
		return this.operater;
	}

	public void setOperater(Operater operater) {
		this.operater = operater;
	}

	@Column(name = "pay_type", nullable = false)
	public int getPayType() {
		return this.payType;
	}

	public void setPayType(int payType) {
		this.payType = payType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pay_time", nullable = false, length = 19)
	public Date getPayTime() {
		return this.payTime;
	}

	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	@Column(name = "amout_pay", nullable = false, precision = 10)
	public double getAmoutPay() {
		return this.amoutPay;
	}

	public void setAmoutPay(double amoutPay) {
		this.amoutPay = amoutPay;
	}

	@Column(name = "dct_pay", nullable = false, precision = 10)
	public double getDctPay() {
		return this.dctPay;
	}

	public void setDctPay(double dctPay) {
		this.dctPay = dctPay;
	}

	@Column(name = "actual_pay", nullable = false, precision = 10)
	public double getActualPay() {
		return this.actualPay;
	}

	public void setActualPay(double actualPay) {
		this.actualPay = actualPay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "del_time", nullable = false, length = 19)
	public Date getDelTime() {
		return this.delTime;
	}

	public void setDelTime(Date delTime) {
		this.delTime = delTime;
	}
	
	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "收费记录 [出入场记录主键=" + adminssionRec.getId() + ", 操作员名称=" + operater.getName() + ", payType=" + payType + ", 付款时间=" + payTime
				+ ", 优惠金额=" + dctPay + ", 应付金额=" + amoutPay + ", 实付金额=" + actualPay + "]";
	}
}
