package com.langmy.terminal.common.entity;

// Generated 2015-2-27 21:26:36 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.langmy.terminal.common.persistence.IdEntityImpl;

/**
 * DelParkingRec generated by hbm2java
 */
@Entity
@Table(name = "del_parking_rec", catalog = "cloud")
public class DelParkingRec extends IdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9088781348190759224L;
	private Car car; //车辆
	private PSp PSp; //车位
	private int adminssionRecId; //出入记录编号
	private Date inTime; //入场时间
	private Date outTime;//出场时间
	private Date delTime; //删除时间

	public DelParkingRec() {
	}

	public DelParkingRec(Car car, PSp PSp, int adminssionRecId, Date inTime,
			Date delTime) {
		this.car = car;
		this.PSp = PSp;
		this.adminssionRecId = adminssionRecId;
		this.inTime = inTime;
		this.delTime = delTime;
	}

	public DelParkingRec(Car car, PSp PSp, int adminssionRecId, Date inTime,
			Date outTime, Date delTime) {
		this.car = car;
		this.PSp = PSp;
		this.adminssionRecId = adminssionRecId;
		this.inTime = inTime;
		this.outTime = outTime;
		this.delTime = delTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "car_id", nullable = false)
	public Car getCar() {
		return this.car;
	}

	public void setCar(Car car) {
		this.car = car;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "p_sp_id", nullable = false)
	public PSp getPSp() {
		return this.PSp;
	}

	public void setPSp(PSp PSp) {
		this.PSp = PSp;
	}

	@Column(name = "adminssion_rec_id", nullable = false)
	public int getAdminssionRecId() {
		return this.adminssionRecId;
	}

	public void setAdminssionRecId(int adminssionRecId) {
		this.adminssionRecId = adminssionRecId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "in_time", nullable = false, length = 19)
	public Date getInTime() {
		return this.inTime;
	}

	public void setInTime(Date inTime) {
		this.inTime = inTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "out_time", length = 19)
	public Date getOutTime() {
		return this.outTime;
	}

	public void setOutTime(Date outTime) {
		this.outTime = outTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "del_time", nullable = false, length = 19)
	public Date getDelTime() {
		return this.delTime;
	}

	public void setDelTime(Date delTime) {
		this.delTime = delTime;
	}

}
