package com.langmy.terminal.common.entity;

// Generated 2015-2-3 18:18:41 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.langmy.terminal.common.persistence.DetailRule;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * MeterCharge generated by hbm2java
 */
@Entity
@Table(name = "meter_charge", catalog = "cloud")
public class MeterCharge extends GenIdEntityImpl implements DetailRule {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1105587339198039404L;
	private String meterChargeId; //计次收费编号
	private String name; //计次收费名称
	private int meteringFree; //计次免费时间/分 
	private double carMetering; //小车计次收费
	private double truckMetering;  //大车计次收费
	private boolean delFlag; //删除标志


	public MeterCharge() {
	}

	public MeterCharge(String meterChargeId, String name, int meteringFree,
			double carMetering, double truckMetering) {
		this.meterChargeId = meterChargeId;
		this.name = name;
		this.meteringFree = meteringFree;
		this.carMetering = carMetering;
		this.truckMetering = truckMetering;
	}


	@Column(name = "meter_charge_id",  length = 30)
	public String getMeterChargeId() {
		return this.meterChargeId;
	}

	public void setMeterChargeId(String meterChargeId) {
		this.meterChargeId = meterChargeId;
	}

	@Column(name = "name",  length = 30)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "metering_free", nullable = false)
	public int getMeteringFree() {
		return this.meteringFree;
	}

	public void setMeteringFree(int meteringFree) {
		this.meteringFree = meteringFree;
	}

	@Column(name = "car_metering", nullable = false, precision = 10)
	public double getCarMetering() {
		return this.carMetering;
	}

	public void setCarMetering(double carMetering) {
		this.carMetering = carMetering;
	}

	@Column(name = "truck_metering", nullable = false, precision = 10)
	public double getTruckMetering() {
		return this.truckMetering;
	}

	public void setTruckMetering(double truckMetering) {
		this.truckMetering = truckMetering;
	}

	@Override
	@Transient
	public String getRuleId() {
		return meterChargeId;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

}
