package com.langmy.terminal.common.entity;

// Generated 2015-2-5 11:56:03 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.PrePersist;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.google.common.collect.Lists;
import com.langmy.terminal.common.persistence.GenIdEntityImpl;
import com.langmy.terminal.common.utils.SetUtils;

/**
 * Operater generated by hbm2java
 */
@Entity
@Table(name = "operater", catalog = "cloud", uniqueConstraints = {
		@UniqueConstraint(columnNames = "id_card"),
		@UniqueConstraint(columnNames = "oper_name") })
public class Operater extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8648404580359516470L;

	private String operName; //用户名
	private String operPwd; //密码
	private int type;// 类型 0:平台 1：终端
	private String name; //姓名
	private String idCard; //身份证号
	private Boolean gender; //性别
	private String job; //职务
	private String picUrl; //头像图片url
	private boolean delFlag; //删除标志
	private boolean enableFlag; //是否启用
	private Date lastDisable; //上一次禁用时间
	private Date createTime; //创建时间
	private Date lastEnable; //上次启用时间
	private List<OperShift> offOperShift = Lists.newArrayList();//操作员交班的交班记录
	private List<OperShift> workOperShift = Lists.newArrayList();//操作员接班的交班记录
	private List<AdminssionRec> inRecs = Lists.newArrayList(); //由该操作员入场的出入场记录
	private List<AdminssionRec> outRecs = Lists.newArrayList(); //由该操作员出场的出入场记录
	private Set<Role> roleList = new HashSet<Role>(0); //角色
	private Set<DelChargeRec> delChargeRecs = new HashSet<DelChargeRec>(0); //已删除收费记录
	private Set<RechargeRec> rechargeRecs = new HashSet<RechargeRec>(0); //充值记录
	private Set<ChargeRec> chargeRecs = new HashSet<ChargeRec>(0); //收费记录
	private Set<OperLiftRec> operLiftRecs = new HashSet<OperLiftRec>(0); //操作员手动抬杆记录



	@Override
	public String toString() {
		return "Operater [用户名=" + operName + ", 密码=" + operPwd + ", 姓名=" + name
				+ ", 身份证号=" + idCard + ", 性别=" + gender + ", 职务=" + job
				+ ", 删除标志=" + delFlag + ", 是否启用=" + enableFlag + ", 上一次禁用时间="
				+ lastDisable + ", 创建时间=" + createTime + ", 上一次启用时间="
				+ lastEnable + "]";
	}

	public Operater() {
	}

	public Operater(String operName, String operPwd, String name,
			String idCard, boolean delFlag, boolean enableFlag,
			Date createTime, Date lastEnable) {
		this.operName = operName;
		this.operPwd = operPwd;
		this.name = name;
		this.idCard = idCard;
		this.delFlag = delFlag;
		this.enableFlag = enableFlag;
		this.createTime = createTime;
		this.lastEnable = lastEnable;
	}

	public Operater(String operName, String operPwd, String name,
			String idCard, Boolean gender, String job,String picUrl, boolean delFlag,
			boolean enableFlag, Date lastDisable, Date createTime,
			Date lastEnable, Set<Role> roleList,
			Set<DelChargeRec> delChargeRecs, Set<RechargeRec> rechargeRecs,
			Set<ChargeRec> chargeRecs, Set<OperLiftRec> operLiftRecs) {
		this.operName = operName;
		this.operPwd = operPwd;
		this.name = name;
		this.idCard = idCard;
		this.gender = gender;
		this.job = job;
		this.picUrl = picUrl;
		this.delFlag = delFlag;
		this.enableFlag = enableFlag;
		this.lastDisable = lastDisable;
		this.createTime = createTime;
		this.lastEnable = lastEnable;
		this.roleList = roleList;
		this.delChargeRecs = delChargeRecs;
		this.rechargeRecs = rechargeRecs;
		this.chargeRecs = chargeRecs;
		this.operLiftRecs = operLiftRecs;
	}

	@PrePersist
	public void prePersist() {
		this.createTime = new Date();
		if (enableFlag) {
			this.lastEnable = new Date();
		} else {
			this.lastDisable = new Date();
		}
	}

	@Column(name = "oper_name", unique = true, nullable = false, length = 20)
	public String getOperName() {
		return this.operName;
	}

	public void setOperName(String operName) {
		this.operName = operName;
	}

	@Column(name = "oper_pwd", nullable = false, length = 100)
	public String getOperPwd() {
		return this.operPwd;
	}

	public void setOperPwd(String operPwd) {
		this.operPwd = operPwd;
	}

	@Column(name = "name", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id_card", unique = true, nullable = false, length = 20)
	public String getIdCard() {
		return this.idCard;
	}

	public void setIdCard(String idCard) {
		this.idCard = idCard;
	}

	@Column(name = "gender")
	public Boolean getGender() {
		return this.gender;
	}

	public void setGender(Boolean gender) {
		this.gender = gender;
	}

	@Column(name = "job", length = 20)
	public String getJob() {
		return this.job;
	}

	public void setJob(String job) {
		this.job = job;
	}
	
	@Column(name = "pic_url", length = 100)
	public String getPicUrl() {
		return this.picUrl;
	}

	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}

	@Column(name = "is_enable", nullable = false)
	public boolean isEnableFlag() {
		return this.enableFlag;
	}

	public void setEnableFlag(boolean enableFlag) {
		this.enableFlag = enableFlag;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_disable", length = 19)
	public Date getLastDisable() {
		return this.lastDisable;
	}

	public void setLastDisable(Date lastDisable) {
		this.lastDisable = lastDisable;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "create_time", nullable = false, length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "last_enable", nullable = false, length = 19)
	public Date getLastEnable() {
		return this.lastEnable;
	}

	public void setLastEnable(Date lastEnable) {
		this.lastEnable = lastEnable;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "oper_role", catalog = "cloud", joinColumns = { @JoinColumn(name = "oper_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) })
	public Set<Role> getRoleList() {
		return this.roleList;
	}

	public void setRoleList(Set<Role> roleList) {
		this.roleList = roleList;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operater")
	public Set<DelChargeRec> getDelChargeRecs() {
		return this.delChargeRecs;
	}

	public void setDelChargeRecs(Set<DelChargeRec> delChargeRecs) {
		this.delChargeRecs = delChargeRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operater")
	public Set<RechargeRec> getRechargeRecs() {
		return this.rechargeRecs;
	}

	public void setRechargeRecs(Set<RechargeRec> rechargeRecs) {
		this.rechargeRecs = rechargeRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operater")
	public Set<ChargeRec> getChargeRecs() {
		return this.chargeRecs;
	}

	public void setChargeRecs(Set<ChargeRec> chargeRecs) {
		this.chargeRecs = chargeRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "operater")
	public Set<OperLiftRec> getOperLiftRecs() {
		return this.operLiftRecs;
	}

	public void setOperLiftRecs(Set<OperLiftRec> operLiftRecs) {
		this.operLiftRecs = operLiftRecs;
	}

	@Transient
	public List<Role> getRoleLists() {
		return SetUtils.convertList(roleList);
	}

	@Transient
	public boolean isAdmin() {
		return this.id == 1 ? true : false;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "inOper")
	public List<AdminssionRec> getInRecs() {
		return inRecs;
	}

	public void setInRecs(List<AdminssionRec> inRecs) {
		this.inRecs = inRecs;
	}
	
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "outOper")
	public List<AdminssionRec> getOutRecs() {
		return outRecs;
	}

	public void setOutRecs(List<AdminssionRec> outRecs) {
		this.outRecs = outRecs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "offWorkOper")
	public List<OperShift> getOffOperShift() {
		return offOperShift;
	}

	public void setOffOperShift(List<OperShift> offOperShift) {
		this.offOperShift = offOperShift;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "workOper")
	public List<OperShift> getWorkOperShift() {
		return workOperShift;
	}

	public void setWorkOperShift(List<OperShift> workOperShift) {
		this.workOperShift = workOperShift;
	}
	
	@Column(name = "type", nullable = false)
	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
