package com.langmy.terminal.common.entity;

// Generated 2015-2-3 18:18:41 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * RechargeRec generated by hbm2java
 */
@Entity
@Table(name = "recharge_rec", catalog = "cloud")
public class RechargeRec extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 941908982565859429L;
	private ChargeRule chargeRule; // 收费规则
	private Operater operater; // 操作员
	private User user; // 客户
	private int rechargeType; // 充值类型 0：用户账户余额充值 1：用户长期用户办理与续费 2：用户租赁车位
	private int rechargeWay; // 充值方式（现金充值/缴费机充值/网上充值）
	private Date beginDate; // 开始日期
	private Date endDate; // 截止日期
	private double money; // 充值金额
	private Date rechargeTime; // 充值时间

	public RechargeRec() {
	}

	public RechargeRec(User user, int rechargeType, int rechargeWay,
			double money, Date rechargeTime) {
		this.user = user;
		this.rechargeType = rechargeType;
		this.rechargeWay = rechargeWay;
		this.money = money;
		this.rechargeTime = rechargeTime;
	}

	public RechargeRec(ChargeRule chargeRule, Operater operater, User user,
			int rechargeType, int rechargeWay, Date beginDate, Date endDate,
			double money, Date rechargeTime) {
		this.chargeRule = chargeRule;
		this.operater = operater;
		this.user = user;
		this.rechargeType = rechargeType;
		this.rechargeWay = rechargeWay;
		this.beginDate = beginDate;
		this.endDate = endDate;
		this.money = money;
		this.rechargeTime = rechargeTime;
	}

	public RechargeRec(Operater operater, User user, Integer rechargeType,
			int rechargeWay, double money, Date rechargeTime) {
		super();
		this.operater = operater;
		this.user = user;
		this.rechargeType = rechargeType;
		this.rechargeWay = rechargeWay;
		this.money = money;
		this.rechargeTime = rechargeTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rent_rule_id")
	public ChargeRule getChargeRule() {
		return this.chargeRule;
	}

	public void setChargeRule(ChargeRule chargeRule) {
		this.chargeRule = chargeRule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "oper_id")
	public Operater getOperater() {
		return this.operater;
	}

	public void setOperater(Operater operater) {
		this.operater = operater;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Column(name = "recharge_type", nullable = false)
	public int getRechargeType() {
		return this.rechargeType;
	}

	public void setRechargeType(int rechargeType) {
		this.rechargeType = rechargeType;
	}

	@Column(name = "recharge_way", nullable = false)
	public int getRechargeWay() {
		return this.rechargeWay;
	}

	public void setRechargeWay(int rechargeWay) {
		this.rechargeWay = rechargeWay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "begin_date", length = 19)
	public Date getBeginDate() {
		return this.beginDate;
	}

	public void setBeginDate(Date beginDate) {
		this.beginDate = beginDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "end_date", length = 19)
	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	@Column(name = "money", nullable = false, precision = 10)
	public double getMoney() {
		return this.money;
	}

	public void setMoney(double money) {
		this.money = money;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "recharge_time", nullable = false, length = 19)
	public Date getRechargeTime() {
		return this.rechargeTime;
	}

	public void setRechargeTime(Date rechargeTime) {
		this.rechargeTime = rechargeTime;
	}

}
