package com.langmy.terminal.common.entity;

// default package
// Generated 2015-1-29 19:22:28 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "cloud", uniqueConstraints = @UniqueConstraint(columnNames = "role_id"))
public class Role extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2637603423935623175L;

	private String roleId; //角色ID
	private String roleName; //角色名
	private String roleDesc; //角色描述
	private boolean delFlag; //删除标志位
	private int type;// 类型 0:平台 1：终端
	private Set<Auth> authList = new HashSet<Auth>(0); //权限
	private Set<Operater> operaterList = new HashSet<Operater>(0); //操作员

	@Override
	public String toString() {
		return "Role [角色ID=" + roleId + ", 角色名称=" + roleName + ", 角色描述="
				+ roleDesc + "]";
	}

	public Role() {
	}

	public Role(String roleId, String roleName) {
		this.roleId = roleId;
		this.roleName = roleName;
	}

	public Role(String roleId, String roleName, String roleDesc,
			Set<Auth> authList, Set<Operater> operaterList) {
		this.roleId = roleId;
		this.roleName = roleName;
		this.roleDesc = roleDesc;
		this.authList = authList;
		this.operaterList = operaterList;
	}

	@Column(name = "role_id", unique = true, nullable = false, length = 20)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "role_name", nullable = false, length = 20)
	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	@Column(name = "role_desc", length = 255)
	public String getRoleDesc() {
		return this.roleDesc;
	}

	public void setRoleDesc(String roleDesc) {
		this.roleDesc = roleDesc;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "role_auth", catalog = "cloud", joinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "auth_id", nullable = false, updatable = false) })
	public Set<Auth> getAuthList() {
		return this.authList;
	}

	public void setAuthList(Set<Auth> authList) {
		this.authList = authList;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "oper_role", catalog = "cloud", joinColumns = { @JoinColumn(name = "role_id", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "oper_id", nullable = false, updatable = false) })
	public Set<Operater> getOperaterList() {
		return this.operaterList;
	}

	public void setOperaterList(Set<Operater> operaterList) {
		this.operaterList = operaterList;
	}

	@Column(name = "del_flag", nullable = false)
	public boolean isDelFlag() {
		return this.delFlag;
	}

	public void setDelFlag(boolean delFlag) {
		this.delFlag = delFlag;
	}
	
	@Column(name = "type", nullable = false)
	public int getType() {
		return type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
