package com.langmy.terminal.common.entity;

// Generated 2015-2-3 18:18:41 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * UGChargeRule generated by hbm2java
 */
@Entity
@Table(name = "u_g_charge_rule", catalog = "cloud")
public class UGChargeRule extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3887069852262719615L;
	private ChargeRule chargeRule; //收费规则
	private UGroup UGroup; //客户组
	private int type; //类型

	public UGChargeRule() {
	}

	public UGChargeRule(ChargeRule chargeRule, UGroup UGroup, int type) {
		this.chargeRule = chargeRule;
		this.UGroup = UGroup;
		this.type = type;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rule_id", nullable = false)
	public ChargeRule getChargeRule() {
		return this.chargeRule;
	}

	public void setChargeRule(ChargeRule chargeRule) {
		this.chargeRule = chargeRule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "u_group_id", nullable = false)
	public UGroup getUGroup() {
		return this.UGroup;
	}

	public void setUGroup(UGroup UGroup) {
		this.UGroup = UGroup;
	}

	@Column(name = "type", nullable = false)
	public int getType() {
		return this.type;
	}

	public void setType(int type) {
		this.type = type;
	}

}
