package com.langmy.terminal.common.entity;

// Generated 2015-2-3 18:18:41 by Hibernate Tools 4.3.1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.langmy.terminal.common.persistence.GenIdEntityImpl;

/**
 * UserPSp generated by hbm2java
 */
@Entity
@Table(name = "user_p_sp", catalog = "cloud")
public class UserPSp extends GenIdEntityImpl {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6314492609536908637L;
	private ChargeRule chargeRule; //收费规则
	private PSp PSp; //停车位
	private User user; //客户
	private Date rentTime; //租用时间
	private double rentFee; //租用费用
	private Date expirationTime; //到期时间

	public UserPSp() {
	}

	public UserPSp(PSp PSp, User user, Date rentTime, double rentFee,
			Date expirationTime) {
		this.PSp = PSp;
		this.user = user;
		this.rentTime = rentTime;
		this.rentFee = rentFee;
		this.expirationTime = expirationTime;
	}

	public UserPSp(ChargeRule chargeRule, PSp PSp, User user, Date rentTime,
			double rentFee, Date expirationTime) {
		this.chargeRule = chargeRule;
		this.PSp = PSp;
		this.user = user;
		this.rentTime = rentTime;
		this.rentFee = rentFee;
		this.expirationTime = expirationTime;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "charge_rule")
	public ChargeRule getChargeRule() {
		return this.chargeRule;
	}

	public void setChargeRule(ChargeRule chargeRule) {
		this.chargeRule = chargeRule;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parking_space_id", nullable = false)
	public PSp getPSp() {
		return this.PSp;
	}

	public void setPSp(PSp PSp) {
		this.PSp = PSp;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "rent_time", nullable = false, length = 19)
	public Date getRentTime() {
		return this.rentTime;
	}

	public void setRentTime(Date rentTime) {
		this.rentTime = rentTime;
	}

	@Column(name = "rent_fee", nullable = false, precision = 10)
	public double getRentFee() {
		return this.rentFee;
	}

	public void setRentFee(double rentFee) {
		this.rentFee = rentFee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "expiration_time", nullable = false, length = 19)
	public Date getExpirationTime() {
		return this.expirationTime;
	}

	public void setExpirationTime(Date expirationTime) {
		this.expirationTime = expirationTime;
	}

}
