var pageUrl={  
        "user_user_list" : "/terminal/user/user/list",
        "user_user_add" : "/terminal/user/user/add",
        "user_user_editAndDbl" : "/terminal/user/user/getUser/",
        "user_user_edit" : "/terminal/user/user/edit",
        "user_user_del" : "/terminal/user/user/del/",
        "user_user_addBlackList" : "/terminal/user/user/addBlackList",
        "user_user_getCar" : "/terminal/user/user/getCar",
        "user_user_getAnchorRents" : "/terminal/user/user/getAnchorRents/",
        "user_user_recharge" : "/terminal/user/user/recharge",
        "user_user_getUserUaccNotBlack" : "/terminal/user/user/getUserUaccNotBlack?",

        "user_blackList_list" : "/terminal/user/blackList/list",
        "user_blackList_getAllUser" : "/terminal/user/blackList/getUsers",
        "user_blackList_add" : "/terminal/user/blackList/add",
        "user_blackList_editAndDbl" : "/terminal/user/blackList/getBlackList/",
        "user_blackList_edit" : "/terminal/user/blackList/edit",
        "user_blackList_recover" : "/terminal/user/blackList/recover",
        "user_blackList_getBlackIds" : "/terminal/user/blackList/getBlackIds?",
        "user_blackList_getUserNames" : "/terminal/user/blackList/getUserNames?",

        "user_userGroup_list" : "/terminal/user/userGroup/list",
        "user_userGroup_enable" : "/terminal/user/userGroup/enable/",
        "user_userGroup_editAndDbl" : "/terminal/user/userGroup/getGroup/",
        "user_userGroup_disable" : "/terminal/user/userGroup/disable/",
        "user_userGroup_getUserGroupId" : "/terminal/user/userGroup/getUserGroupId",
        "user_userGroup_getDctRuleGroup" : "/terminal/user/userGroup/getDctRuleGroup",
        "user_userGroup_getChargeRuleLong" : "/terminal/user/userGroup/getChargeRuleLong",
        "user_userGroup_getChargeRuleCountOrTime" : "/terminal/user/userGroup/getChargeRuleCountOrTime",
        "user_userGroup_add" : "/terminal/user/userGroup/add",
        "user_userGroup_delValidate" : "/terminal/user/userGroup/delValidate/",
        "user_userGroup_edit" : "/terminal/user/userGroup/edit",
        "user_userGroup_del" : "/terminal/user/userGroup/del/",
        "user_userGroup_getNameId" : "/terminal/user/userGroup/getNameId?",
        "user_userGroup_getNameName" : "/terminal/user/userGroup/getNameName?",
        "user_userGroup_getUidUid" : "/terminal/user/userGroup/getUidUid?",
        "user_userGroup_getMemberUGroupNameId" : "/terminal/user/userGroup/getMemberUGroupNameId?",
        "user_userGroup_getLongMemberUGroupNameId" : "/terminal/user/userGroup/getLongMemberUGroupNameId?",
        "user_userGroup_getTempUGroupNameId" : "/terminal/user/userGroup/getTempUGroupNameId?",
        "user_userGroup_getNotlongNameId" : "/terminal/user/userGroup/getNotlongNameId?",

    	"caradmission_admissRec_list" : "/terminal/caradmission/admissRec/list",
		"caradmission_admissRec_del" : "/terminal/caradmission/admissRec/del/",
		"caradmission_admissRec_editAndDblUrl" : "/terminal/caradmission/admissRec/getAdminssion/",
		"caradmission_admissRec_edit" : "/terminal/caradmission/admissRec/edit/",
		"caradmission_admissRec_licensePlate" : "/terminal/caradmission/admissRec/licensePlate?",
		"caradmission_admissRec_type" : "/terminal/caradmission/admissRec/getType?",
		"caradmission_admissRec_entrance" : "/terminal/caradmission/admissRec/getEntrance?",
		"caradmission_admissRec_exit" : "/terminal/caradmission/admissRec/getExit?",

		"caradmission_car_list" : "/terminal/caradmission/car/list",
		"caradmission_car_del" : "/terminal/caradmission/car/del/",
		"caradmission_car_typeName" : "/terminal/caradmission/car/typeName?",
		"caradmission_car_module" : "/terminal/caradmission/car/module?",
		"caradmission_car_color" : "/terminal/caradmission/car/color?",
		"caradmission_car_users" : "/terminal/caradmission/car/getUserNotBlackAndIsEnable?",
		"caradmission_car_dbl" : "/terminal/caradmission/car/getUser/",
		"caradmission_car_add" : "/terminal/caradmission/car/add",
		"caradmission_car_getCar" : "/terminal/caradmission/car/getCar/",
		"caradmission_car_edit" : "/terminal/caradmission/car/edit",
		"caradmission_car_addColor" : "/terminal/caradmission/carType/addColor",
		"caradmission_car_addType" : "/terminal/caradmission/carType/addType",
		"caradmission_car_addModule" : "/terminal/caradmission/carType/addModule",
		"caradmission_car_ifExist" : "/terminal/caradmission/car/ifExist",
		"caradmission_car_licensePlate" : "/terminal/caradmission/car/licensePlate?",

		"caradmission_carType_typeList" : "/terminal/caradmission/carType/typeList",
		"caradmission_carType_colorList" : "/terminal/caradmission/carType/colorList",
		"caradmission_carType_moduleList" : "/terminal/caradmission/carType/moduleList",
		"caradmission_carType_del" : "/terminal/caradmission/carType/del/",
		"caradmission_carType_addColor" : "/terminal/caradmission/carType/addColor",
		"caradmission_carType_addType" : "/terminal/caradmission/carType/addType",
		"caradmission_carType_addModule" : "/terminal/caradmission/carType/addModule",

		"caradmission_exit_getData" : "/terminal/caradmission/exit/getData",
		"caradmission_exit_complete" : "/terminal/caradmission/exit/complete",
		"caradmission_exit_blacklist" : "/terminal/caradmission/exit/blacklist",
		"caradmission_exit_matching" : "/terminal/caradmission/exit/matching",

		"caradmission_parkingRec_list" : "/terminal/caradmission/parkingRec/list",
		"caradmission_parkingRec_editAndDbl" : "/terminal/caradmission/parkingRec/getParkingRec/",
		"caradmission_parkingRec_del" : "/terminal/caradmission/parkingRec/del/",
		"caradmission_parkingRec_type" : "/terminal/caradmission/parkingRec/getType?",
		"caradmission_parkingRec_licensePlate" : "/terminal/caradmission/parkingRec/licensePlate?",
		"caradmission_parkingRec_pspId" : "/terminal/caradmission/parkingRec/pspId?",

		"charge_anchorGroup_list" : "/terminal/charge/anchorGroup/list",
		"charge_anchorGroup_editAndDbl" : "/terminal/charge/anchorGroup/getAnchorGroup/",
		"charge_anchorGroup_getAnchorGroupId" : "/terminal/charge/anchorGroup/getAnchorGroupId",
		"charge_anchorGroup_add" : "/terminal/charge/anchorGroup/add",
		"charge_anchorGroup_edit" : "/terminal/charge/anchorGroup/edit",
		"charge_anchorGroup_editRulesInGroup" : "/terminal/charge/anchorGroup/editRulesInGroup",
		"charge_anchorGroup_getAnchorRents" : "/terminal/charge/anchorRent/allAnchorRents",
		"charge_anchorGroup_del" : "/terminal/charge/anchorGroup/del/",
		"charge_anchorGroup_delValidate" : "/terminal/charge/anchorGroup/delValidate/",
		
		"charge_anchorRent_list" : "/terminal/charge/anchorRent/list",
		"charge_anchorRent_editAndDbl" : "/terminal/charge/anchorRent/getAnchorRent/",
		"charge_anchorRent_getAnchorRentId" :"/terminal/charge/anchorRent/getAnchorRentId",
		"charge_anchorRent_add" : "/terminal/charge/anchorRent/add",
		"charge_anchorRent_edit" : "/terminal/charge/anchorRent/edit",
		"charge_anchorRent_del" : "/terminal/charge/anchorRent/del/",

		"charge_chargeRec_list" : "/terminal/charge/chargeRec/list",
		"charge_chargeRec_editAndDbl" : "/terminal/charge/chargeRec/getChargeRec/",

		"charge_chargeRule_list" : "/terminal/charge/chargeRule/list",
		"charge_chargeRule_editAndDbl" : "/terminal/charge/chargeRule/getChargeRule/",
		"charge_chargeRule_getChargeRuleId" : "/terminal/charge/chargeRule/getChargeRuleId",
		"charge_chargeRule_add" : "/terminal/charge/chargeRule/add",
		"charge_chargeRule_edit" : "/terminal/charge/chargeRule/edit",
		"charge_chargeRule_delValidate" : "/terminal/charge/chargeRule/delValidate/",
		"charge_chargeRule_del" : "/terminal/charge/chargeRule/del/",

		"charge_dctRule_list" : "/terminal/charge/dctRule/list",
		"charge_dctRule_editAndDbl" : "/terminal/charge/dctRule/getDctRule/",
		"charge_dctRule_getDctRuleId" : "/terminal/charge/dctRule/getDctRuleId",
		"charge_dctRule_add" : "/terminal/charge/dctRule/add",
		"charge_dctRule_edit" : "/terminal/charge/dctRule/edit",
		"charge_dctRule_del" :"/park/charge/dctRule/del/",
		
		"charge_dctRuleGroup_list" : "/terminal/charge/dctRuleGroup/list",
		"charge_dctRuleGroup_editAndDbl" : "/terminal/charge/dctRuleGroup/getDctRuleGroup/",
		"charge_dctRuleGroup_getDctRuleGroupId" : "/terminal/charge/dctRuleGroup/getDctRuleGroupId",
		"charge_dctRuleGroup_add" : "/terminal/charge/dctRuleGroup/add",
		"charge_dctRuleGroup_edit" : "/terminal/charge/dctRuleGroup/edit",
		"charge_dctRuleGroup_editRulesInGroup" : "/terminal/charge/dctRuleGroup/editRulesInGroup",
		"charge_dctRuleGroup_getDctRules" : "/terminal/charge/dctRule/getDctRules",
		"charge_dctRuleGroup_delValidate" : "/terminal/charge/dctRuleGroup/delValidate/",
		"charge_dctRuleGroup_del" : "/terminal/charge/dctRuleGroup/del/",

		"charge_delChargeRec_list" : "/terminal/charge/delChargeRec/list",
		"charge_delChargeRec_editAndDbl" : "/terminal/charge/delChargeRec/getDelChargeRec/",

		"device_bayonet_list" : "/terminal/device/bayonet/list",
		"device_bayonet_editAndDbl" : "/terminal/device/bayonet/getBayonet/",
		"device_bayonet_getBayonetId" : "/terminal/device/bayonet/getBayonetId",
		"device_bayonet_add" : "/terminal/device/bayonet/add",
		"device_bayonet_edit" : "/terminal/device/bayonet/edit",
		"device_bayonet_getSameBayonetId" : "/terminal/device/bayonet/getSameBayonetId",
		"device_bayonet_del" : "/terminal/device/bayonet/del/",
		"device_bayonet_getBayonet" : "/terminal/device/bayonet/getBayonet?",
		
		"device_camera_list" : "/terminal/device/camera/list",
		"device_camera_editAndDbl" : "/terminal/device/camera/getCamera/",
		"device_camera_getCameraId" : "/terminal/device/camera/getCameraId",
		"device_camera_add" : "/terminal/device/camera/add",
		"device_camera_edit" : "/terminal/device/camera/edit",
		"device_camera_getDriveway" : "/terminal/device/camera/getDriveway?",
		"device_camera_del" : "/terminal/device/camera/del/",
		"device_camera_enable" : "/park/device/camera/enable/",
		"device_camera_disable" : "/park/device/camera/disable/",

		"device_pSpLock_list" : "/terminal/device/pSpLock/list",
		"device_pSpLock_editAndDbl" : "/terminal/device/pSpLock/getLock/",
		"device_pSpLock_add" : "/terminal/device/pSpLock/add",
		"device_pSpLock_edit" : "/terminal/device/pSpLock/edit",
		"device_pSpLock_getPspId" : "/terminal/device/pSpLock/getPspId?",
		"device_pSpLock_del" : "/terminal/device/pSpLock/del/",
		"device_pSpLock_enable" :  "/park/device/pSpLock/openLock/",
		"device_pSpLock_disable" :  "/park/device/pSpLock/closeLock/",

		"device_deviceAll_list" : "/terminal/device/deviceAll/list",
		"device_deviceAll_editAndDbl" : "/terminal/device/deviceAll/getDevice/",
		"device_deviceAll_getDeviceId" : "/terminal/device/deviceAll/getDeviceId",
		"device_deviceAll_add" : "/terminal/device/deviceAll/add",
		"device_deviceAll_edit" : "/terminal/device/deviceAll/edit",
		"device_deviceAll_enableBrake" : "/terminal/device/deviceAll/enableBrake/",
		"device_deviceAll_disableBrake" : "/terminal/device/deviceAll/disableBrake/",
		"device_deviceAll_getBayonet" : "/terminal/device/deviceAll/getBayonet?",
		"device_deviceAll_del" : "/terminal/device/deviceAll/del/",
		"device_deviceAll_brakeList" : "/terminal/device/deviceAll/brakeList",
		"device_deviceAll_paymentList" : "/terminal/device/deviceAll/paymentList",
		"device_deviceAll_terminalList" : "/terminal/device/deviceAll/terminalList",
		"device_deviceAll_integratedList" : "/terminal/device/deviceAll/integratedList",
		"device_deviceAll_dataMasterList" : "/terminal/device/deviceAll/dataMasterList",
		"device_driveway_getAllDrivewaySelect" : "/terminal/device/driveway/getAllDrivewaySelect",
		"device_driveway_getExistDrivewaySelect" : "/terminal/device/driveway/getExistDrivewaySelect",

		"device_screen_list" : "/terminal/device/screen/list",
		"device_screen_editAndDbl" : "/terminal/device/screen/getLedScreen/",
		"device_screen_getLedScreenId" : "/terminal/device/screen/getLedScreenId",
		"device_screen_add" : "/terminal/device/screen/add",
		"device_screen_edit" : "/terminal/device/screen/edit",
		"device_screen_configure" : "/terminal/device/screen/configure",
		"device_screen_getAreas" : "/terminal/device/screen/getAreas",
		"device_screen_editScreenArea" : "/terminal/device/screen/getScreenArea/",
		"device_screen_getDataMaster" : "/terminal/device/screen/getDataMaster?/",
		"device_screen_del" : "/terminal/device/screen/del/",

		"device_driveway_list" : "/terminal/device/driveway/list",
		"device_driveway_editAndDbl" : "/terminal/device/driveway/getDriveway/",
		"device_driveway_getDrivewayId" : "/terminal/device/driveway/getDrivewayId",
		"device_driveway_add" : "/terminal/device/driveway/add",
		"device_driveway_edit" : "/terminal/device/driveway/edit",
		"device_driveway_getSameDrivewayId" : "/terminal/device/driveway/getSameDrivewayId",
		"device_driveway_del" : "/terminal/device/driveway/del/",
		"device_driveway_getBayonet" : "/terminal/device/driveway/getBayonet?",
		"device_driveway_getBrake" : "/terminal/device/driveway/getBrake?",
		"device_driveway_getScreen" : "/terminal/device/driveway/getScreen?",
		"device_driveway_getDriveway" : "/terminal/device/driveway/getDriveway?",
		"device_driveway_getDrivewayIn" : "/terminal/device/driveway/getDrivewayIn?",
		"device_driveway_getDrivewayOut" : "/terminal/device/driveway/getDrivewayOut?",
		"device_driveway_getScreenIn" : "/terminal/device/driveway/getScreenIn?",
		"device_driveway_getScreenOut" :"/terminal/device/driveway/getScreenOut?",
		"device_driveway_config" : "/terminal/device/driveway/config",

		"device_park_add" : "/terminal/device/park/add",
		"device_park_edit" : "/terminal/device/park/edit",
		"device_park_editAndDbl" : "/terminal/device/park/getPark/",
		"device_park_del" : "/terminal/device/park/delete/",
		"device_park_getChargeRule" : "/terminal/device/park/getChargeRule",
		"device_park_getSameParkName" : "/terminal/device/park/getSameParkName",
		"device_bayonet_list" : "/terminal/device/bayonet/list",
		"device_bayonet_addBayonet" : "/terminal/device/bayonet/add",
		"device_bayonet_editBayonet" : "/terminal/device/bayonet/edit",
		"device_bayonet_delBayonet" : "/terminal/device/bayonet/del/",
		"device_bayonet_editAndDblBayonet" : "/terminal/device/bayonet/getBayonet/",
		"device_bayonet_getBayonetId" : "/terminal/device/bayonet/getBayonetId",

		"log_list" : "/terminal/log/list",
		"log_del" : "/terminal/log/del/",

		"report_charRec_list" : "/terminal/report/charRec/list",
		"report_charRec_del" : "/terminal/report/charRec/del/",
		"report_charRec_search" : "/terminal/report/charRec/search",

		"report_operLaundryList_list" : "/report/operLaundryList/list",
		
		"report_operLiftRec_list" : "/terminal/report/operLiftRec/list",
		"report_operLiftRec_del" : "/terminal/report/operLiftRec/del/",
		"report_operLiftRec_search" : "/terminal/report/operLiftRec/search",

		"report_reCharRec_list" : "/terminal/report/reCharRec/list",
		"report_reCharRec_search" : "/terminal/report/reCharRec/search",

		"system_parkingEnvir_getData" : "/terminal/admin/sys/parkingEnvir/getParkingEnvir",
		"system_parkingEnvir_save" : "/terminal/admin/sys/parkingEnvir/edit",
		"system_parkingEnvir_backup" : "/terminal/admin/sys/parkingEnvir/backup",
		"system_parkingEnvir_load" : "/terminal/admin/sys/parkingEnvir/load",

		"system_operater_getOperNames" : "/terminal/admin/sys/operater/getOperNames?",
		"system_operater_getOperIds" : "/terminal/admin/sys/operater/getOperIds?",
		"system_operater_getNames" : "/terminal/admin/sys/operater/getNames?",

};